### ISSUE TITLE
Warn when read orientation autodetect flips orientation?

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#103]
**Improvement Description**
Silently flipping the read orientation might give surprising results. 

Suggest warning when the autodetector detects reversed read orientation. (It will be a two-liner.)

**References**
1. There is an [issue on the forum](https://forum.qiime2.org/t/same-classifier-same-otu-different-sequencing-run-different-classification/3975).

**Comment by gregcaporaso** [comment]
We don't have a cross-interface system in place for issuing warnings, and this doesn't seem to have been an issue in practice, so I'm going to close this one.
