### ISSUE TITLE
Reduce memory requirements for classifier

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#12]
... by removing `pandas.Series` dependency and maybe writing a custom output type.

**Comment by BenKaehler** [comment]
@ebolyen has some advice: https://qiime2.slack.com/archives/developers/p1473259232000007

**Comment by gregcaporaso** [comment]
@BenKaehler, I think this was taken care of the epic #47. Closing, but if I'm wrong about this just re-open the issue.

**Comment by BenKaehler** [comment]
Thanks @gregcaporaso, this enhancement could still be made, but it would be premature optimisation so keep it closed.
