### ISSUE TITLE
`classify-sklearn`: MemoryError should be more user-friendly

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-classifier#131]
**Improvement Description**
Report some troubleshooting steps in the error message

**Current Behavior**
the raw `MemoryError` message is reported

**Proposed Behavior**
Catch memory error and give a better message. Mention:
1. `reads-per-batch` parameter
2. issues with parallel jobs
3. try a smaller database
4. get a more powerful machine or allocate more resources

**Comment by David-Rod** [comment]
Hey @nbokulich, I know that you are currently working on the new release, but I was hoping to get some more context for this issue. Would you be able to provide the steps and files that are needed to replicate the `MemoryError` for this issue? I have been trying to replicate on my own, but I have been unsuccessful so far. Thanks.

**Comment by nbokulich** [comment]
hey @David-Rod to be honest I don't have a good test example because I have not run into this issue before (it is usually encountered if you have a weak system or unusually large data).

I recommend grabbing the full-length SILVA classifier and classifying any 16S sequences. A great way to eat up more memory is to run with `n_jobs > 1`

**Comment by David-Rod** [comment]
@nbokulich  So I used the full-length SILVA classifier, and I received the following:

![image](https://user-images.githubusercontent.com/30784905/62166993-013d0600-b2d7-11e9-8319-e20004c524f5.png)

Does this look similar to the error you might have received? I have received no messages in my terminal as of now. My machine is just spinning.

**Comment by nbokulich** [comment]
yikes! no I have not encountered that before. It is surprising the
MemoryError has not been raised.

**Comment by thermokarst** [comment]
Hi @David-Rod --- that looks like a _disk space_ error, not a memory (RAM) error. One possibility for testing memory errors is to adjust the ulimit settings on your development machine to artificially "lower" the available memory.

**Comment by nbokulich** [comment]
is this issue resolved? I see there was some discussion over whether @David-Rod 's changes covered all memory errors, but it looks like @ebolyen 's changes may have fixed this?
