### ISSUE TITLE
joblib now a dependency in scikit-learn

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-feature-classifier#134]
**Bug Description**
Scikit-learn recently [spun off `joblib` as a dependency](https://scikit-learn.org/stable/whats_new.html#miscellaneous), removing it from the scikit-learn codebase. 

When QIIME 2 v2019.4 is updated with `scikit-learn v21.1`,  `q2-feature classifier` throws a deprecation warning when running `fit-classifier-naive-bayes`:
```
/scratch/crk239/conda-envs/q2-19.4/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: $
 warnings.warn(msg, category=DeprecationWarning)
```

This has not been extensively tested, but likely impacts other sklearn-based Actions as well.
q2-feature-classifier should be refactored as needed to handle the change of `joblib` from vendored to dependency software. 

**Expected behavior**
`fit-classifier-naive-bayes` (and other Actions) should complete without deprecation warnings

**Computation Environment**
- OS: CentOS 6.10
- slurm 18.08.7
- QIIME 2 Release 2019.4

**References**
1. https://scikit-learn.org/stable/whats_new.html#miscellaneous

**Comment by thermokarst** [comment]
cc @nbokulich && @BenKaehler

**Comment by thermokarst** [comment]
Let's address this in 2019.7.
