### ISSUE TITLE
`extract-reads`: add n-jobs parameter

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-feature-classifier#135]
**Improvement Description**
It looks like it may be possible to meaningfully parallelize `extract-reads` based on [this forum post](https://forum.qiime2.org/t/specifying-how-many-threads-to-run-on-with-qiime2-feature-classifier-extract-reads/10111/5).

We would need this to be done via some kind of multi-processing workflow (hence jobs not threads), but joblib might make this easy-ish.

**Questions**
1. At some point we will definitely become IO-bound, what is that point? Should there be a maximum set for the number of jobs, since even an NVMe SSD will eventually tap out.

**Comments**
1. It may be worth verifying CPU vs disk IO before starting this in earnest.

**References**
1. https://forum.qiime2.org/t/specifying-how-many-threads-to-run-on-with-qiime2-feature-classifier-extract-reads/10111/5

**Comment by BenKaehler** [comment]
This has been on my todo list for ages.

The process only has IO at the start and end and it is negligible.

I will parallelise it consistent with read classification (using joblib).

**Comment by Oddant1** [comment]
I'm interested in taking a stab at this issue
