### ISSUE TITLE
Fix warnings in unit tests

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#142]
**Bug Description**
The unit tests throw up a bunch of warnings. [See the attached output.](https://github.com/qiime2/q2-feature-classifier/files/3388149/divide-by-zero-warnings.log) Two are easy fixes and not concerning. One is a divide by zero in a part of the code that we use all the time, so we should probably check it out. The tests seem to pass, however.

**Steps to reproduce the behavior**
Run `make test-cov`.

**Expected behavior**
It would be nice if the tests completed without warnings.

**Computation Environment**
- OS: Ubuntu 18.10
- QIIME 2 Release 2019.4

**Comment by nbokulich** [comment]
I cannot replicate the warning that you are getting in your log using the development build, @BenKaehler . [Travis appears to agree with me](https://travis-ci.org/qiime2/q2-feature-classifier/builds/558068089?utm_source=github_status&utm_medium=notification) for once. Specifically, the divide by zero warning is absent and must be a feature of your local env.

**Comment by BenKaehler** [comment]
I was testing on 2019.4 (my bad). Thank you for transforming this issue into a sleeping dog.
