### ISSUE TITLE
classify-consensus-vsearch: expose maxhits option (and other options)

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-classifier#151]
**Improvement Description**
Expose vsearch maxhits option, which explicitly controls the number of hits that are reported. 

While we're at it, expose some more options to make behavior more flexible: `maxrejects` (default 0), `output_no_hits` (default `True`), `weak_id` (default None), anything else?

**Current Behavior**
maxaccepts (currently exposed) implicitly controls the number of hits reported, but will return > 1 hit if `strand=both` and two different sequences are hit. See: https://github.com/torognes/vsearch/issues/388#issuecomment-539009338

**Proposed Behavior**
maxhits would make it very clear how many hits are reported, e.g., supporting arbitrary top-hit searches.

**Comment by splaisan** [comment]
Hi,
It would be supercool if you could also expose maxrejects which is now default to 0 if I read well.
Best

ref: https://groups.google.com/forum/#!searchin/vsearch-forum/maxrejects/vsearch-forum/xwlzDbL91Cc/JpIIF7gfDAAJ

**Comment by nbokulich** [comment]
> It would be supercool if you could also expose maxrejects which is now default to 0 if I read well.

Yep, already done, see the PR above. Thanks!

**Comment by splaisan** [comment]
any news about when this will be pushed to the latest build? (when is 2020.2?)
thanks
