### ISSUE TITLE
Wrap makeblastdb to generate indexed blast database

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-classifier#158]
**Improvement Description**
Hi, is there any chance you could wrap makeblastdb, so that classify-consensus-blast first creates a blast-indexed database starting from the fasta file included in the FeatureData[Sequence] artifact, and then performs the alignment (specifying -db instead of -subject), so that it can be run with multi-threading?
Thanks,
Simone

**References**
_Originally posted by @MaestSi in https://github.com/qiime2/q2-feature-classifier/issues/155#issuecomment-592580404_

**Comment by nbokulich** [comment]
Thanks for the suggestion @MaestSi !

I considered it when putting this together originally... since using an indexed db would also speed up blast somewhat. Making this as a separate method would not be trivial, though, since a new format would need to be created for the indexed db.

Another option (maybe what you are suggesting) would be to run makeblastdb as part of `classify-consensus-blast` so that the blasting step could run with multithreading, and this would be easier to accomplish.

We would certainly welcome a PR if you are interested in contributing this! Otherwise this will probably be a pretty low priority for us, since my sense is that classify-consensus-blast is not very commonly used. In the meantime, `classify-consensus-vsearch` enables multithreading, maybe this would be a viable substitute for you (even though it's a global aligner)?

**Comment by MaestSi** [comment]
Yes, my suggestion was to run makeblastdb as part of classify-consensus-blast. Unfortunately I can’t contribute as I don’t know python programming, otherwise I would love to. I’ll try out classify-consensus-vsearch with the new options available in the coming q2 release. As of now, it is not a viable substitute as it is much slower despite multi-threading.
Thanks,
Simone
