### ISSUE TITLE
Testing classifier issue - Parameter 'confidence' received -1 as an argument, which is incompatible with parameter type: Float % Range(0, 1, inclusive_end=True) | Str % Choices('disable')

### ISSUE THREAD

**Issue by XrandallX** [qiime2/q2-feature-classifier#174]
# Hello,
# I also received an original error message when trying to test the classifier 
# I am using a functional genes database for mcrA

######################
######################
qiime feature-classifier classify-sklearn \
  --i-classifier classifier.qza \
  --i-reads Xrep_set85nonchimeras.qza \
  --o-classification taxonomy.qza

# This was the error message which as I understand is related to my inputted taxonomy file that has incomplete lineages

Plugin error from feature-classifier:

  pop from empty list

# I tried to correct by the following addition to the code based on the following thread
# https://forum.qiime2.org/t/plugin-error-from-feature-classifier-pop-from-empty-list/1431/11

qiime feature-classifier classify-sklearn --i-reads rep-seqs.qza --i-classifier classifier.qza --o-classification result.qza --p-confidence -1 --p-read-orientation same

# This is the new error I received regarding the --p- confidence -1 section below

Plugin error from feature-classifier:

Parameter 'confidence' received -1 as an argument, which is incompatible with parameter type: Float % Range(0, 1, inclusive_end=True) | Str % Choices('disable')

Debug info has been saved to /tmp/qiime2-q2cli-err-dc8df57b.log

# Would anyone have any insight please? 
# Thanks, Kate

**Comment by nbokulich** [comment]
Please post all user support questions to the QIIME 2 forum. Thank you.
