### ISSUE TITLE
confidence calculations could be improved

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#18]
**Current Behavior**
Currently we're calculating confidence in the [same way that RDP does](http://aem.asm.org/content/73/16/5261). For a sequence of length n and k-mers of length k, draw n/k bootstraps with replacement. Repeat 100 times and see how many times we get the same prediction as our original sequence at each level.

It works ok for naive bayes, but for the ensemble methods for which I've done limited testing it does not do very well. Perhaps this is because each bootstrap doesn't resemble the real data much.

Unfortunately it's [hard to do much better](https://www.kevinsheppard.com/images/0/0a/Kreiss_and_lahiri.pdf), not least because the literature doesn't seem to address our situation much: small sample size with strong dependence and categorical samples. Also, bootstraps are slow.

**Proposed Behavior**
We could perhaps use a jackknife approach, but I can't find anything useful in the literature.

An alternative is [probability calibration](http://scikit-learn.org/stable/modules/calibration.html). If it worked, it would be much faster than bootstraps. It would need to be thoroughly tested and compared with the RDP approach. Changes on the classifier fitting side should be minimal, but the classification side would need a small rewrite. 

**References**
1. [same way that RDP does](http://aem.asm.org/content/73/16/5261)
2. [hard to do much better](https://www.kevinsheppard.com/images/0/0a/Kreiss_and_lahiri.pdf)
3. [probability calibration](http://scikit-learn.org/stable/modules/calibration.html)

**Comment by BenKaehler** [comment]
Probability calibration doesn't work because each class is calibrated separately, which means that we must either drop classifications with too few samples or have very dodgy calibrations.

Another option is to make use of the actual uncertainty around the calls made by the clustering or dada2 step.

**Comment by gregcaporaso** [comment]
I'm going to close this one as it's been open for a while and no one has jumped in on it. If there is still interest in this, feel free to reopen.
