### ISSUE TITLE
Higher RAM use in classify-consensus-vsearch version 2022.8+

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-classifier#188]
**Bug Description**
A [forum user reports](https://forum.qiime2.org/t/problem-with-feature-classifier-classify-consensus-vsearch/25368/6?u=nicholas_bokulich) higher RAM use with `classify-consensus-vsearch` in version 2022.8, but not in 2022.2

I have not confirmed this yet, but opening this ticket to remind me or anyone interested to investigate.

2022.8 introduced some significant changes in #176 that were intended to increase efficiency, but by decoupling the alignment and consensus classification steps it is possible that [pure speculation here] RAM usage is increasing because the alignment results are also written out as an intermediate output.

**References**
[forum x-ref](https://forum.qiime2.org/t/problem-with-feature-classifier-classify-consensus-vsearch/25368/6?u=nicholas_bokulich)

**Comment by vaamb** [comment]
I observed the same behaviour during my analyses and it seems that it is due to pandas `replace`

I made a pull request (#189) with the modifications that solved this issue for me
