### ISSUE TITLE
Using new NCBI 4 experimental taxonomic nt databases for qiime2 classifer

### ISSUE THREAD

**Issue by jibrantahir** [qiime2/q2-feature-classifier#200]
Hi , I am interested to use some specific databases in qiime2 from NCBI- https://ftp.ncbi.nlm.nih.gov/blast/db/
I am familiar with this post https://forum.qiime2.org/t/using-rescript-to-compile-sequence-databases-and-taxonomy-classifiers-from-ncbi-genbank/15947
But , this post doesnt not cover if we have to download some new databases and how to handle taxonomy from NCBI. For example in the link below, NCBI- https://ftp.ncbi.nlm.nih.gov/blast/db/, there are 4 experimental taxonomic nt databases released , eukaryotes, prokaryotes, viruses and others. The tar.gz files are in found in the link. How to use them for qiime2
many thanks
Jibran

**Comment by nbokulich** [comment]
Hi @jibrantahir for QIIME 2 usage questions and technical support please post your question in the QIIME 2 forum. Thank you!
