### ISSUE TITLE
Clarify vsearch's bitscores and evalues

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2-feature-classifier#203]
**Improvement Description**
Clarify why vsearch does not output the same bitscores and evalues as blast.

**Current Behavior**
After running a vsearch plugin, all outputs bitscores are all 0 and all evalues -1

📑 

>Warning, vsearch uses global pairwise alignments, not blast’s seed-and-extend algorithm. Therefore, some common blast output values (alignment start and end, evalue, bit score) are reported differently.
>...
>
>evalue: expectancy-value (not computed for nucleotide alignments). Always set to -1.
>bits: bit score (not computed for nucleotide alignments). Always set to 0.

**Questions**
Should we:
Drop these columns from the vsearch output, as they are not useful.
or
Clarify why they are always 0 and -1

**Comments**
[forums x-ref](https://forum.qiime2.org/t/bitscore-and-evalue-after-running-qiime-feature-classifier-classify-consensus-vsearch/30296)

**References**
[vsearch manual pdf](https://github.com/torognes/vsearch/releases/download/v2.28.1/vsearch_manual.pdf) search for 'evalue'

**Comment by nbokulich** [comment]
We should not drop these columns, as this would break the format (vsearch conveniently outputs a blast6 format output).

Clarification is a better solution, but this is probably better placed in a tutorial (or other documentation) than in q2-feature-classifier. We do not currently have a tutorial for using vsearch-global or classify-consensus-vsearch, but that's where I would put any explanation of the outputs.

Though honestly this is the first time this question was ever asked in the past 6 years, and now there is a great answer by you @colinbrislawn that we can point to on the forum if anyone else asks, so I am not sure that this is an issue that needs to be fixed.

**Comment by colinbrislawn** [comment]
Well said. These columns are already well documented in vsearch, so perhaps a forums post and GitHub issue is enough for now. :shipit:

I appreciate your insight about where and how to write docs.
