### ISSUE TITLE
memory usage for training-classifier

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2-feature-classifier#204]
## Memory usage currently scales at 1.1*io_out

[forums x-ref](https://forum.qiime2.org/t/memory-usage-for-skl-nb-classifier/30817).

unite: ver9  25.07.2023 
qiime2-2023.5
[download here v9.0-v25.07.2023-qiime2-2023.5](https://github.com/colinbrislawn/unite-train/releases/tag/v9.0-v25.07.2023-qiime2-2023.5
)

![image](https://github.com/user-attachments/assets/ceba65d3-c034-460d-af56-cabe6be532a2)

I suppose this makes sense as all seen k-mers must stay in memory...

**Comment by nbokulich** [comment]
thanks @colinbrislawn ! I do not see an issue here yet, so I will close this down as you cross-posted on the forum so we can carry on discussion there instead. We can re-open this later if this is tied to a specific issue.
