### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#54]
**Comments**
Unit tests are required for

- `classifier.pipeline_from_spec`
- `classifier.spec_from_pipeline`
- `custom.LowMemoryMultinomialNB`
- `custom._MultioutputClassifier`

**Comment by BenKaehler** [comment]
All done except for `custom._MultioutputClassifier`

**Comment by gregcaporaso** [comment]
`MultioutputClassifier` doesn't seem to be used anywhere, so I'm going to close this since all other unit tests tagged here were addressed.
