### ISSUE TITLE
`fit-classifier-naive-bayes` default chunk size to 20000

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-classifier#57]
Discussed this with @BenKaehler on Slack - this will speed up the classifier and avoid memory errors.

**Comment by jairideout** [comment]
Woops, tagged the wrong Ben!

cc: @BenKaehler

**Comment by gregcaporaso** [comment]
Thanks @jairideout!

**Comment by gregcaporaso** [comment]
@BenKaehler, I got an error using a chunk size of 20000 this morning:

```
Plugin error from feature-classifier:

  index out of bounds: 0 <= 0 <= 855, 0 <= 20000 <= 855, 0 <= 20000

Re-run with --verbose to see debug info.
```

I was able to correct this easily my self (by just going with the default of -1), but if we make 20000 the default we'll need to handle this case so users don't get the error - basically we'll just need to detect when 20k isn't a sensible value, and go with something that is.
