### ISSUE TITLE
naive bayes classifiers don't work if reads are reverse complement relative to the reference database

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-classifier#58]
I ran into some very strange results when analyzing 454 data that I imported at the `FeatureTable[Frequency]` and `FeatureData[Sequence]` stage. These are skin samples from the [Fierer et al "Keyboard Study"](http://www.pnas.org/content/107/14/6477.full). 

My initial taxonomy barplots looked like this, which are clearly not the right composition:

![screenshot 2017-03-29 14 39 16](https://cloud.githubusercontent.com/assets/192372/24477960/e7b746bc-148d-11e7-9dca-65bc0200b9b1.png)

After spending some time figuring out what was going on, and noticing that the `blast+` assigner in the current development version was giving correct results, I realized that in the `FeatureData[Sequence]` data that I was importing, the sequences are actually the reverse complement relative to what's in Greengenes. I reverse complemented all of my sequences before importing, and the resulting taxa compositions look correct:

![screenshot 2017-03-29 14 39 23](https://cloud.githubusercontent.com/assets/192372/24478035/362211c4-148e-11e7-971e-ed25b9c17238.png)

`blast+` is handling this because it searches for both forward/forward and forward/reverse matches, and I think RDP classifier handles it by training on the forward and reverse complement kmers. @nbokulich, @BenKaehler, does that sound right to you? 

Could we update the naive bayes classifiers, and any others that would have this same issue, to work both for reads that are forward and reverse complement relative to the training data?

**Comment by BenKaehler** [comment]
Thanks @gregcaporaso, according to Wang (2007), for the online version of the RDP classifier at least,

> The Classifier automatically checks both the forward and reverse orientations of the sequence and returns only the results for the correct orientation.

I think this is probably the correct approach, that is to attempt to classify the forward and reverse reads, rather than to make the classifier's job even harder by throwing the reverse complements at it as well in the training step.

Is it valid to assume that all of the reads in a sample are forward or all of the reads are reversed? We could check the first 1000 in both directions, then pick the direction that's giving more "confident" classifications for the rest of the run.

**Comment by nbokulich** [comment]
I think that most cases will have all forward or all reverse reads. I can imagine a scenario where mixed 16S orientations exist, but this doesn't fit any current library prep method that I know, so don't think it is necessary to support — just checking the first N reads makes sense as long as this is documented well.

But what about shotgun metagenome sequencing reads? One might wish to pull out 16S contigs (or other marker genes) and classify using ``q2-feature-classifier``, and these could be in mixed orientations (I think). Just something to think about.

@gregcaporaso vsearch already supports aligning forward/both orientations so no changes needed there.

**Comment by BenKaehler** [comment]
Hi @gregcaporaso, could you please do me a favour and send me your data from the above examples? Thanks!
