### ISSUE TITLE
vsearch classifier method: odd parameter name

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-feature-classifier#60]
The `vsearch` method has a parameter with an odd name. In the CLI it is `--p-id-`, and in the Python code I'm guessing it is called `id_`. @nbokulich does it make sense to rename this parameter to match `blast`, i.e. `--p-perc-identity`?

Example:

<img width="582" alt="screen shot 2017-03-31 at 12 27 07 pm" src="https://cloud.githubusercontent.com/assets/1847232/24567461/b25e93b8-1612-11e7-86c9-300b347f06d6.png">

**Comment by nbokulich** [comment]
Thanks for catching this — yep, it is called ``id_``, merely because I was trying to adhere to the original param names in vsearch (where it is called ``id``). I am fine calling this ``perc_identity`` to match ``blast`` or ``max_id``, the name I originally gave this param.
