### ISSUE TITLE
add default confidence value > 0.0 for classify-sklearn

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-classifier#64]
The current default (-1.0) doesn't compute confidence scores. This can give very misleading results in some cases. For example, I accidentally used a 515F/806R classifier on data that was sequenced with 27F/338R with the default of no confidence estimation. I got species-level assignments, but they were nowhere near the right taxa. Since there were no confidence estimates, there was no indication that anything was wrong with the results. When I re-ran the data with higher confidence values (0.8 and 0.5) I only had assignments of _bacteria_ (in a few bases, a phylum-level assignment was also made with confidence=0.5). Indicating that they were unassigned would have been ideal, but in this case I could clearly see that there was a problem. I'm labeling this as a bug because there is a very real potential for users to get a silent failure like the one I'm describing here. 

@BenKaehler and @nbokulich are going to make a decision on a default value to start with based on their on-going parameter sweep/optimization. 

Also, when using a value other than -1.0 for confidence, the confidence scores will be included in the `FeatureData[Taxonomy]`'s data. It would be really nice if ``qiime taxa tabulate`` could present these values as well (it could just present all of the information in the `data/taxonomy.tsv` file). This is secondary to the main point of this issue though, which is just starting to use a confidence value > 0.0.

**Comment by BenKaehler** [comment]
Just as a note, we should add `'fit_prior': False` to the naïve Bayes classifier definition at the same time. This follows from rather lengthier conversations I've had with @nbokulich.

**Comment by BenKaehler** [comment]
On this matter:

> Also, when using a value other than -1.0 for confidence, the confidence scores will be included in the FeatureData[Taxonomy]'s data. It would be really nice if qiime taxa tabulate could present these values as well (it could just present all of the information in the data/taxonomy.tsv file). This is secondary to the main point of this issue though, which is just starting to use a confidence value > 0.0.

Should that more properly be raised as an issue in `q2-taxa`?

**Comment by jairideout** [comment]
👍, and it's not something we'd need to have in this release (unless anyone has bandwidth to work on it). I created an issue on q2-taxa: https://github.com/qiime2/q2-taxa/issues/74
