### ISSUE TITLE
Make API consistent for classifiers?

### ISSUE THREAD

**Issue by johnchase** [qiime2/q2-feature-classifier#72]
**Improvement Description**
I wonder if would be possible to make the api consistent across the different classifiers? The two that I am most familiar with are the naive bayes classifier and the blast classifier. I apologize If there is already a way to do this that I have missed.

## Use case 
We often perform analyses across many runs so we have created a pipeline for most processes, including assigning taxonomy. Being able to swap out classifiers would be great for testing, and if new classifiers were added they could be added with almost no overhead. 

## Example of different APIs:
```python 
#bayes classifier
bayes_classifier = '/home/john/classifiers/bayes_classifier.qza'
classifier = qiime2.Artifact.load(bayes_classifier)
classifier_function = feature_classifier.methods.classify
taxa_assignments = classifier_function(reads=seqs, classifier=classifier)

#blast classifier
rep_tax = qiime2.Artifact.load('/home/john/classifiers/gg_tax_99.qza')
rep_seqs_99_amplicon = qiime2.Artifact.load('/home/john/classifiers/gg_seqs_99_515f_806r.qza')
taxa_assignments = feature_classifier.methods.classify_consensus_blast(query=seqs, 
                                                                       reference_reads=rep_seqs_99_amplicon, 
                                                                       reference_taxonomy=rep_tax)
```
I really like the API in the first example as it makes it very easy to try out a lot of different classifiers quickly. Additionally we will share classifiers between users. The first API allows a classifier to be shared without having to specify multiple parameters and reference files.

## Possible solution:
```python 
blast_classifer = feature_classifier.methods.create_blast_classifier(reference_reads=rep_seqs_99_amplicon,
                                                                     reference_taxonomy=rep_tax)

blast_classifier.save('/home/john/classifiers/blast_classifier.qza')

blast_classifier_fp = '/home/john/classifiers/blast_classifier.qza'
blast_classifier = qiime2.Artifact.load(blast_classifier_fp)
classifier_function = feature_classifier.methods.classify
taxa_assignments = classifier_function(reads=seqs, classifier=blast_classifier)
```

## Explanation
I realize that in the example of the bayes classifier the classifier needs to be "trained" - not something that is necessary with the BLAST classifier, however a classifier could still be created and then used in the `classfier_function` above. 

Hopefully this makes sense, and I am fully understanding the requirements of the different classifications methods. I am curious to know if this would be useful for others.

**Comment by gregcaporaso** [comment]
I'm going to close this as we haven't had activity on it in several years, but feel free to re-open if there's still interest in this.
