### ISSUE TITLE
ENH: use metadata to input class priors

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#76]
**Current Behavior**
It is currently impossible to input class priors on the command line as command line commands cannot exceed a fixed, platform dependent limit.

**Proposed Behavior**
A solution is to use metadata (http://qiime.org/documentation/file_formats.html#metadata-mapping-files) to optionally input class priors. We can't use Artifacts because Artifacts can't be optional.

**Reference**
1. A workaround is here: https://github.com/BenKaehler/q2-extra-classifier (see the qiime_kludge command line utility).
2. http://qiime.org/documentation/file_formats.html#metadata-mapping-files

**Comment by jairideout** [comment]
Just a note that we're shooting to have optional artifact support for the next release (2017.6, scheduled for June 14 release date).

**Comment by gregcaporaso** [comment]
I believe this is addressed in [q2-clawback](https://github.com/BenKaehler/q2-clawback).
