### ISSUE TITLE
ChunkedHashingVectorizer is not compatible with sklearn 0.19.0

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-feature-classifier#84]
[This testing log](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-feature-classifier/builds/65) shows the issue. It looks like a parameter was removed (or perhaps it became keyword only?). In any case, a `super().transform` method has a different signature now.

**Comment by thermokarst** [comment]
Hey @BenKaehler, do you have time to look at this for this release (2017.8) or the next release (2017.9)? If we tried to get this in for 2017.8, a PR would need to get in this week some time (we are shooting for a release on August 30th). No worries if you don't have the bandwidth to look into this right now, please just let us know either way. Thanks!

**Comment by BenKaehler** [comment]
Thanks Matt, I'll try to get this done this week.
